[package]
name = "rvm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
notify = "8.1.0"
serde_json = "1.0.142"
thiserror = "2.0.12"
tokio = { version = "1.47.0", features = ["full"] }
